/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './components/**/*.{js,vue,ts}',
    './layouts/**/*.vue',
    './pages/**/*.vue',
    './plugins/**/*.{js,ts}',
    './app.vue',
    './error.vue',
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        'headline-sm': ['Inter'],
        'headline-lg': ['Inter'],
        'headline-md': ['Inter'],
        'data-mono': ['Inter'],
        'body-sm': ['Inter'],
        'body-md': ['Inter'],
        'body-lg': ['Inter'],
        'label-bold': ['Inter'],
      },
      fontSize: {
        'headline-sm': ['18px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-lg': ['30px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'data-mono':   ['14px', { lineHeight: '20px', letterSpacing: '-0.01em', fontWeight: '500' }],
        'body-sm':     ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'body-md':     ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-lg':     ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-bold':  ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
      },
      colors: {
        // ── Qurban Monitor (index) ──
        'qurban-dark':   '#0f4c3a',
        'qurban-green':  '#198754',
        'qurban-orange': '#f39c12',
        'qurban-red':    '#dc3545',
        'qurban-purple': '#6f42c1',
        'qurban-teal':   '#20c997',
        'qurban-blue':   '#0d6efd',
        'qurban-bg':     '#f8f9fa',
        'step-blue':     '#2b78e4',
        'step-green':    '#27a844',
        'step-orange':   '#fd7e14',
        'step-purple':   '#6f42c1',
        'step-teal':     '#20c997',

        // ── Admin Panel ──
        'on-primary':                  '#ffffff',
        'secondary-container':         '#86f2e4',
        'on-tertiary-container':       '#ea9e93',
        'surface-bright':              '#f6fafe',
        'status-unpaid':               '#EF4444',
        'on-primary-fixed-variant':    '#0b513d',
        'on-tertiary-fixed-variant':   '#6e372f',
        'on-surface':                  '#171c1f',
        'primary':                     '#003527',
        'on-background':               '#171c1f',
        'primary-fixed':               '#b0f0d6',
        'surface-container':           '#eaeef2',
        'surface-variant':             '#dfe3e7',
        'on-secondary-container':      '#006f66',
        'on-primary-fixed':            '#002117',
        'tertiary':                    '#4f1f19',
        'on-secondary-fixed':          '#00201d',
        'tertiary-fixed':              '#ffdad5',
        'error':                       '#ba1a1a',
        'secondary-fixed-dim':         '#6bd8cb',
        'outline':                     '#707974',
        'inverse-surface':             '#2c3134',
        'error-container':             '#ffdad6',
        'on-error':                    '#ffffff',
        'surface-tint':                '#2b6954',
        'tertiary-fixed-dim':          '#ffb4a9',
        'primary-fixed-dim':           '#95d3ba',
        'surface-container-highest':   '#dfe3e7',
        'secondary-fixed':             '#89f5e7',
        'on-tertiary':                 '#ffffff',
        'outline-variant':             '#bfc9c3',
        'surface':                     '#f6fafe',
        'status-completed':            '#16A34A',
        'on-tertiary-fixed':           '#380d08',
        'on-surface-variant':          '#404944',
        'border-subtle':               '#E2E8F0',
        'background':                  '#f6fafe',
        'status-pending':              '#F59E0B',
        'secondary':                   '#006a61',
        'inverse-on-surface':          '#edf1f5',
        'on-error-container':          '#93000a',
        'tertiary-container':          '#6b342d',
        'on-secondary-fixed-variant':  '#005049',
        'primary-container':           '#064e3b',
        'surface-container-low':       '#f0f4f8',
        'sidebar-dark':                '#022C22',
        'inverse-primary':             '#95d3ba',
        'on-secondary':                '#ffffff',
        'on-primary-container':        '#80bea6',
        'surface-container-high':      '#e4e9ed',
        'surface-container-lowest':    '#ffffff',
        'surface-dim':                 '#d6dade',
      },
      spacing: {
        'stack-sm':       '0.5rem',
        'stack-md':       '1rem',
        'stack-lg':       '2rem',
        'gutter':         '1.5rem',
        'margin-edge':    '2rem',
        'container-max':  '1440px',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg:      '0.25rem',
        xl:      '0.5rem',
        full:    '0.75rem',
      },
      maxWidth: {
        'container-max': '1440px',
      },
    },
  },
  plugins: [],
}