-- =========================================================================
-- COMBINED MIGRATION SCRIPT
-- Urutan: Reset → DDL → Seed → Views → Functions → Triggers → RLS → Users
-- =========================================================================


-- =========================================================================
-- BAGIAN 0: RESET — Hapus semua objek lama
-- =========================================================================
DROP VIEW IF EXISTS public.v_grup_progress;

DROP TABLE IF EXISTS public.foto_lapangan    CASCADE;
DROP TABLE IF EXISTS public.activity_logs    CASCADE;
DROP TABLE IF EXISTS public.sohibul_qurban   CASCADE;
DROP TABLE IF EXISTS public.grup_hewan       CASCADE;
DROP TABLE IF EXISTS public.users            CASCADE;

DROP TYPE IF EXISTS user_role_enum;


-- =========================================================================
-- BAGIAN 1: TIPE ENUM
-- =========================================================================
CREATE TYPE user_role_enum AS ENUM (
    'sembelihan',   -- Khusus Area Sembelih (Akses ubah via QR Scan)
    'pengulitan',   -- Khusus Area Pengulitan (Akses ubah via QR Scan)
    'ketua'         -- Ketua / Koordinator Lapangan
);


-- =========================================================================
-- BAGIAN 2: DDL — Buat Tabel Parent: grup_hewan
-- =========================================================================
CREATE TABLE public.grup_hewan (
    id_grup            VARCHAR(50)  PRIMARY KEY,
    jenis_hewan        VARCHAR(20)  NOT NULL,
    label_tampilan     VARCHAR(100) NOT NULL,
    status_kedatangan  VARCHAR(20)  DEFAULT 'Belum' CHECK (status_kedatangan  IN ('Belum', 'Proses', 'Selesai')),
    status_sembelihan  VARCHAR(20)  DEFAULT 'Belum' CHECK (status_sembelihan  IN ('Belum', 'Proses', 'Selesai')),
    status_pengulitan  VARCHAR(20)  DEFAULT 'Belum' CHECK (status_pengulitan  IN ('Belum', 'Proses', 'Selesai')),
    status_pengemasan  VARCHAR(20)  DEFAULT 'Belum' CHECK (status_pengemasan  IN ('Belum', 'Proses', 'Selesai')),
    keterangan         VARCHAR(255) NULL DEFAULT '-',
    created_at         TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Aktifkan realtime untuk dashboard TV
ALTER TABLE public.grup_hewan REPLICA IDENTITY FULL;


-- =========================================================================
-- BAGIAN 3: DDL — Buat Tabel Child: sohibul_qurban
-- =========================================================================
CREATE TABLE public.sohibul_qurban (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama        VARCHAR(255) NOT NULL,
    jenis_hewan VARCHAR(20)  NOT NULL,
    jatah       INT          NOT NULL DEFAULT 1,
    id_grup     TEXT         REFERENCES public.grup_hewan(id_grup) ON DELETE CASCADE,
    created_at  TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);


-- =========================================================================
-- BAGIAN 4: DDL — Buat Tabel Users / Anggota Tim Lapangan
-- =========================================================================
CREATE TABLE public.users (
    id         UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    nama       VARCHAR(100)    NOT NULL,
    role       user_role_enum  NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);


-- =========================================================================
-- BAGIAN 5: FUNGSI & TRIGGER
-- =========================================================================
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;


-- =========================================================================
-- BAGIAN 6: ROW LEVEL SECURITY
-- =========================================================================
ALTER TABLE public.grup_hewan     DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.sohibul_qurban DISABLE ROW LEVEL SECURITY;

-- activity_logs & foto_lapangan dinonaktifkan juga (tabel dibuat oleh migration lain)
-- ALTER TABLE public.activity_logs  DISABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.foto_lapangan  DISABLE ROW LEVEL SECURITY;

-- Users: aktifkan RLS dengan kebijakan publik bisa baca & insert (untuk gate onboarding)
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access on users"
    ON public.users FOR SELECT USING (true);

CREATE POLICY "Allow anon insert from gate onboarding"
    ON public.users FOR INSERT WITH CHECK (true);


-- =========================================================================
-- BAGIAN 7: SEED DATA — grup_hewan
--    4 Kelompok Sapi + 28 Domba Individu + 10 Kambing Individu
-- =========================================================================
INSERT INTO public.grup_hewan (id_grup, jenis_hewan, label_tampilan) VALUES
-- Kelompok Sapi Kolektif
('SAPI-01', 'Sapi', 'KOLEKTIF SAPI KE-1'),
('SAPI-02', 'Sapi', 'KOLEKTIF SAPI KE-2'),
('SAPI-03', 'Sapi', 'KOLEKTIF SAPI KE-3'),
('SAPI-04', 'Sapi', 'KOLEKTIF SAPI KE-4'),

-- Domba Individu
('DOMBA-01', 'Domba', 'Sis Dwi adi'),
('DOMBA-02', 'Domba', 'Suyadi bin supardi'),
('DOMBA-03', 'Domba', 'Nijma dan keluarga'),
('DOMBA-04', 'Domba', 'Purwanto'),
('DOMBA-05', 'Domba', 'Elsa Erlian binti Sariono'),
('DOMBA-06', 'Domba', 'Eko Sugeng Cahyono & keluarga'),
('DOMBA-07', 'Domba', 'Munawar Hasim'),
('DOMBA-08', 'Domba', 'Wakhidin bin Carya'),
('DOMBA-09', 'Domba', 'Hermawan'),
('DOMBA-10', 'Domba', 'Zulfahmi'),
('DOMBA-11', 'Domba', 'Ibu Djumroh'),
('DOMBA-12', 'Domba', 'Hanyfah Putri Azahra'),
('DOMBA-13', 'Domba', 'Radityo'),
('DOMBA-14', 'Domba', 'Sutanto Dwiantoro'),
('DOMBA-15', 'Domba', 'Suhardi'),
('DOMBA-16', 'Domba', 'Yusuf'),
('DOMBA-17', 'Domba', 'Riki agustian & Keluarga'),
('DOMBA-18', 'Domba', 'Gilang & Keluarga'),
('DOMBA-19', 'Domba', 'Reza syam pratama'),
('DOMBA-20', 'Domba', 'Maulana Hidayat'),
('DOMBA-21', 'Domba', 'Priangga Budi Setyo'),
('DOMBA-22', 'Domba', 'Syamsul Ma''arif'),
('DOMBA-23', 'Domba', 'Bapak Indri sahfriaji'),
('DOMBA-24', 'Domba', 'Andi Parwanto'),
('DOMBA-25', 'Domba', 'Harni Siswati'),
('DOMBA-26', 'Domba', 'M. Rayhan Fuadi & istri'),
('DOMBA-27', 'Domba', 'Rika Binti Taslim'),
('DOMBA-28', 'Domba', 'Dwi Hastuti Achwari'),

-- Kambing Individu
('KAMBING-01', 'Kambing', 'Bu Sunarti'),
('KAMBING-02', 'Kambing', 'Saryono'),
('KAMBING-03', 'Kambing', 'NUR KHOLIS'),
('KAMBING-04', 'Kambing', 'Wiwit Lestari'),
('KAMBING-05', 'Kambing', 'Supriyo'),
('KAMBING-06', 'Kambing', 'Suhadi Mulyono'),
('KAMBING-07', 'Kambing', 'Wasbari'),
('KAMBING-08', 'Kambing', 'Afra Nabilla Pramudifa'),
('KAMBING-09', 'Kambing', 'Moh Tarmidi'),
('KAMBING-10', 'Kambing', 'Hermanto');


-- =========================================================================
-- BAGIAN 8: SEED DATA — sohibul_qurban (64 pequrban)
-- =========================================================================
INSERT INTO public.sohibul_qurban (nama, jenis_hewan, jatah, id_grup) VALUES
-- ── KOLEKTIF SAPI KE-1 (7 orang) ──
('Abimanyu Gatya Dhaneswara',        'Sapi', 1, 'SAPI-01'),
('Untung Dedi & keluarga',           'Sapi', 1, 'SAPI-01'),
('Aip Abu Salwa & keluarga',         'Sapi', 1, 'SAPI-01'),
('Didik Purwanto & keluarga',        'Sapi', 1, 'SAPI-01'),
('Abu Asyraf & keluarga',            'Sapi', 1, 'SAPI-01'),
('Sholikhun & keluarga',             'Sapi', 1, 'SAPI-01'),
('Affan Faris',                      'Sapi', 1, 'SAPI-01'),

-- ── KOLEKTIF SAPI KE-2 (7 orang) ──
('Rahmatika',                        'Sapi', 1, 'SAPI-02'),
('Winarko',                          'Sapi', 1, 'SAPI-02'),
('Ismaniar',                         'Sapi', 1, 'SAPI-02'),
('Yahya Tanpono (Bida Sari)',        'Sapi', 1, 'SAPI-02'),
('Taufiq Nugroho',                   'Sapi', 1, 'SAPI-02'),
('Sri Yuniarti',                     'Sapi', 1, 'SAPI-02'),
('Trinanto',                         'Sapi', 1, 'SAPI-02'),

-- ── KOLEKTIF SAPI KE-3 (7 orang) ──
('Dwi Winarso / Abu Yazid',          'Sapi', 1, 'SAPI-03'),
('Yogi Adi Pradana',                 'Sapi', 1, 'SAPI-03'),
('Sidik',                            'Sapi', 1, 'SAPI-03'),
('Firmansyah',                       'Sapi', 1, 'SAPI-03'),
('Yoga Pratama',                     'Sapi', 1, 'SAPI-03'),
('Sulaiman Abdul Malik',             'Sapi', 1, 'SAPI-03'),
('Muhammad Samroni bin Abdul Qadir', 'Sapi', 1, 'SAPI-03'),

-- ── KOLEKTIF SAPI KE-4 (4 orang) ──
('Mahmuri',                          'Sapi', 1, 'SAPI-04'),
('Kartika Aji & keluarga',           'Sapi', 1, 'SAPI-04'),
('Zulkarnaen',                       'Sapi', 1, 'SAPI-04'),
('Dimyati',                          'Sapi', 1, 'SAPI-04'),

-- ── DOMBA INDIVIDU (28 orang) ──
('Sis Dwi adi',                      'Domba', 1, 'DOMBA-01'),
('Suyadi bin supardi',               'Domba', 1, 'DOMBA-02'),
('Nijma dan keluarga',               'Domba', 1, 'DOMBA-03'),
('Purwanto',                         'Domba', 1, 'DOMBA-04'),
('Elsa Erlian binti Sariono',        'Domba', 1, 'DOMBA-05'),
('Eko Sugeng Cahyono & keluarga',    'Domba', 1, 'DOMBA-06'),
('Munawar Hasim',                    'Domba', 1, 'DOMBA-07'),
('Wakhidin bin Carya',               'Domba', 1, 'DOMBA-08'),
('Hermawan',                         'Domba', 1, 'DOMBA-09'),
('Zulfahmi',                         'Domba', 1, 'DOMBA-10'),
('Ibu Djumroh',                      'Domba', 1, 'DOMBA-11'),
('Hanyfah Putri Azahra',             'Domba', 1, 'DOMBA-12'),
('Radityo',                          'Domba', 1, 'DOMBA-13'),
('Sutanto Dwiantoro',                'Domba', 1, 'DOMBA-14'),
('Suhardi',                          'Domba', 1, 'DOMBA-15'),
('Yusuf',                            'Domba', 1, 'DOMBA-16'),
('Riki agustian & Keluarga',         'Domba', 1, 'DOMBA-17'),
('Gilang & Keluarga',                'Domba', 1, 'DOMBA-18'),
('Reza syam pratama',                'Domba', 1, 'DOMBA-19'),
('Maulana Hidayat',                  'Domba', 1, 'DOMBA-20'),
('Priangga Budi Setyo',              'Domba', 1, 'DOMBA-21'),
('Syamsul Ma''arif',                 'Domba', 1, 'DOMBA-22'),
('Bapak Indri sahfriaji',            'Domba', 1, 'DOMBA-23'),
('Andi Parwanto',                    'Domba', 1, 'DOMBA-24'),
('Harni Siswati',                    'Domba', 1, 'DOMBA-25'),
('M. Rayhan Fuadi & istri',          'Domba', 1, 'DOMBA-26'),
('Rika Binti Taslim',                'Domba', 1, 'DOMBA-27'),
('Dwi Hastuti Achwari',              'Domba', 1, 'DOMBA-28'),

-- ── KAMBING INDIVIDU (10 orang) ──
('Bu Sunarti',                       'Kambing', 1, 'KAMBING-01'),
('Saryono',                          'Kambing', 1, 'KAMBING-02'),
('NUR KHOLIS',                       'Kambing', 1, 'KAMBING-03'),
('Wiwit Lestari',                    'Kambing', 1, 'KAMBING-04'),
('Supriyo',                          'Kambing', 1, 'KAMBING-05'),
('Suhadi Mulyono.',                  'Kambing', 1, 'KAMBING-06'),
('Wasbari',                          'Kambing', 1, 'KAMBING-07'),
('Afra Nabilla Pramudifa',           'Kambing', 1, 'KAMBING-08'),
('Moh Tarmidi',                      'Kambing', 1, 'KAMBING-09'),
('Hermanto',                         'Kambing', 1, 'KAMBING-10');


-- =========================================================================
-- VERIFIKASI (opsional — jalankan terpisah setelah seeding)
-- =========================================================================
-- SELECT jenis_hewan, COUNT(*) AS jumlah FROM public.sohibul_qurban GROUP BY jenis_hewan;
-- SELECT g.label_tampilan, COUNT(s.id) AS anggota
--   FROM public.grup_hewan g
--   LEFT JOIN public.sohibul_qurban s ON s.id_grup = g.id_grup
--  GROUP BY g.label_tampilan ORDER BY g.id_grup;